# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_element.ui'
#
# Created: Fri May 02 20:23:32 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(326, 452)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 281, 151))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(11, 61, 261, 22))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.ele_w_Edit = QtGui.QLineEdit(self.widget)
        self.ele_w_Edit.setMinimumSize(QtCore.QSize(50, 0))
        self.ele_w_Edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ele_w_Edit.setObjectName(_fromUtf8("ele_w_Edit"))
        self.horizontalLayout.addWidget(self.ele_w_Edit)
        self.ele_h_Edit = QtGui.QLineEdit(self.widget)
        self.ele_h_Edit.setMinimumSize(QtCore.QSize(50, 0))
        self.ele_h_Edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ele_h_Edit.setObjectName(_fromUtf8("ele_h_Edit"))
        self.horizontalLayout.addWidget(self.ele_h_Edit)
        self.widget1 = QtGui.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(11, 20, 261, 24))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_14 = QtGui.QLabel(self.widget1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_2.addWidget(self.label_14)
        self.ele_type_comboBox = QtGui.QComboBox(self.widget1)
        self.ele_type_comboBox.setMinimumSize(QtCore.QSize(130, 22))
        self.ele_type_comboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.ele_type_comboBox.setObjectName(_fromUtf8("ele_type_comboBox"))
        self.ele_type_comboBox.addItem(_fromUtf8(""))
        self.ele_type_comboBox.addItem(_fromUtf8(""))
        self.ele_type_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.ele_type_comboBox)
        self.widget2 = QtGui.QWidget(self.groupBox)
        self.widget2.setGeometry(QtCore.QRect(10, 110, 264, 22))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_16 = QtGui.QLabel(self.widget2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_7.addWidget(self.label_16)
        self.left_margin_Edit = QtGui.QLineEdit(self.widget2)
        self.left_margin_Edit.setMinimumSize(QtCore.QSize(50, 0))
        self.left_margin_Edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_margin_Edit.setObjectName(_fromUtf8("left_margin_Edit"))
        self.horizontalLayout_7.addWidget(self.left_margin_Edit)
        self.top_margin_Edit = QtGui.QLineEdit(self.widget2)
        self.top_margin_Edit.setMinimumSize(QtCore.QSize(50, 0))
        self.top_margin_Edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.top_margin_Edit.setObjectName(_fromUtf8("top_margin_Edit"))
        self.horizontalLayout_7.addWidget(self.top_margin_Edit)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 180, 281, 171))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 60, 261, 22))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.col_num_Edit = QtGui.QLineEdit(self.layoutWidget_3)
        self.col_num_Edit.setMinimumSize(QtCore.QSize(130, 0))
        self.col_num_Edit.setMaximumSize(QtCore.QSize(130, 16777215))
        self.col_num_Edit.setObjectName(_fromUtf8("col_num_Edit"))
        self.horizontalLayout_4.addWidget(self.col_num_Edit)
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 120, 261, 22))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.v_space_Edit = QtGui.QLineEdit(self.layoutWidget_4)
        self.v_space_Edit.setMinimumSize(QtCore.QSize(130, 0))
        self.v_space_Edit.setMaximumSize(QtCore.QSize(130, 16777215))
        self.v_space_Edit.setObjectName(_fromUtf8("v_space_Edit"))
        self.horizontalLayout_6.addWidget(self.v_space_Edit)
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 90, 261, 22))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.h_space_Edit = QtGui.QLineEdit(self.layoutWidget_5)
        self.h_space_Edit.setMinimumSize(QtCore.QSize(130, 0))
        self.h_space_Edit.setMaximumSize(QtCore.QSize(130, 16777215))
        self.h_space_Edit.setObjectName(_fromUtf8("h_space_Edit"))
        self.horizontalLayout_5.addWidget(self.h_space_Edit)
        self.layoutWidget_6 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 30, 261, 22))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.row_num_Edit = QtGui.QLineEdit(self.layoutWidget_6)
        self.row_num_Edit.setMinimumSize(QtCore.QSize(130, 0))
        self.row_num_Edit.setMaximumSize(QtCore.QSize(130, 16777215))
        self.row_num_Edit.setObjectName(_fromUtf8("row_num_Edit"))
        self.horizontalLayout_3.addWidget(self.row_num_Edit)
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 390, 120, 23))
        self.pushButton.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton.setSizeIncrement(QtCore.QSize(1, 0))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "添加元素", None))
        self.groupBox.setTitle(_translate("Dialog", "元素属性", None))
        self.label_12.setText(_translate("Dialog", "元素尺寸(宽x高):", None))
        self.ele_w_Edit.setText(_translate("Dialog", "200", None))
        self.ele_h_Edit.setText(_translate("Dialog", "80", None))
        self.label_14.setText(_translate("Dialog", "元素类型:", None))
        self.ele_type_comboBox.setItemText(0, _translate("Dialog", "请选择", None))
        self.ele_type_comboBox.setItemText(1, _translate("Dialog", "条形码", None))
        self.ele_type_comboBox.setItemText(2, _translate("Dialog", "二维码", None))
        self.label_16.setStatusTip(_translate("Dialog", "距离上边缘和左边缘的位置", None))
        self.label_16.setText(_translate("Dialog", "首元素位置(距左边和上边):", None))
        self.left_margin_Edit.setText(_translate("Dialog", "20", None))
        self.top_margin_Edit.setText(_translate("Dialog", "20", None))
        self.groupBox_2.setTitle(_translate("Dialog", "排列属性", None))
        self.label_5.setText(_translate("Dialog", "列数:", None))
        self.col_num_Edit.setText(_translate("Dialog", "1", None))
        self.label_6.setText(_translate("Dialog", "垂直间距:", None))
        self.v_space_Edit.setText(_translate("Dialog", "10", None))
        self.label_7.setText(_translate("Dialog", "水平间距:", None))
        self.h_space_Edit.setText(_translate("Dialog", "10", None))
        self.label_4.setText(_translate("Dialog", "行数:", None))
        self.row_num_Edit.setText(_translate("Dialog", "1", None))
        self.pushButton.setText(_translate("Dialog", "确定添加", None))

