# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'carve.ui'
#
# Created: Sat Mar 29 23:16:36 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(794, 586)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 781, 531))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.imageLabel = QtGui.QLabel(self.widget)
        self.imageLabel.setObjectName(_fromUtf8("imageLabel"))
        self.horizontalLayout.addWidget(self.imageLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_7 = QtGui.QLabel(self.widget)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.capture_btn = QtGui.QPushButton(self.widget)
        self.capture_btn.setObjectName(_fromUtf8("capture_btn"))
        self.gridLayout_5.addWidget(self.capture_btn, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.leftEdit = QtGui.QLineEdit(self.widget)
        self.leftEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.leftEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.leftEdit.setObjectName(_fromUtf8("leftEdit"))
        self.gridLayout.addWidget(self.leftEdit, 0, 1, 1, 1)
        self.leftBtn = QtGui.QPushButton(self.widget)
        self.leftBtn.setMinimumSize(QtCore.QSize(50, 0))
        self.leftBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leftBtn.setObjectName(_fromUtf8("leftBtn"))
        self.gridLayout.addWidget(self.leftBtn, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rightEdit_2 = QtGui.QLineEdit(self.widget)
        self.rightEdit_2.setMinimumSize(QtCore.QSize(40, 0))
        self.rightEdit_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rightEdit_2.setObjectName(_fromUtf8("rightEdit_2"))
        self.gridLayout_2.addWidget(self.rightEdit_2, 0, 1, 1, 1)
        self.rightBtn_2 = QtGui.QPushButton(self.widget)
        self.rightBtn_2.setMinimumSize(QtCore.QSize(50, 0))
        self.rightBtn_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.rightBtn_2.setObjectName(_fromUtf8("rightBtn_2"))
        self.gridLayout_2.addWidget(self.rightBtn_2, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.upEdit = QtGui.QLineEdit(self.widget)
        self.upEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.upEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.upEdit.setObjectName(_fromUtf8("upEdit"))
        self.gridLayout_3.addWidget(self.upEdit, 0, 1, 1, 1)
        self.upBtn = QtGui.QPushButton(self.widget)
        self.upBtn.setMinimumSize(QtCore.QSize(50, 0))
        self.upBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.upBtn.setObjectName(_fromUtf8("upBtn"))
        self.gridLayout_3.addWidget(self.upBtn, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.downEdit = QtGui.QLineEdit(self.widget)
        self.downEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.downEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.downEdit.setObjectName(_fromUtf8("downEdit"))
        self.gridLayout_4.addWidget(self.downEdit, 0, 1, 1, 1)
        self.downBtn = QtGui.QPushButton(self.widget)
        self.downBtn.setMinimumSize(QtCore.QSize(50, 0))
        self.downBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.downBtn.setObjectName(_fromUtf8("downBtn"))
        self.gridLayout_4.addWidget(self.downBtn, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menu)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_4 = QtGui.QMenu(self.menubar)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menu_5 = QtGui.QMenu(self.menubar)
        self.menu_5.setObjectName(_fromUtf8("menu_5"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.actionF = QtGui.QAction(MainWindow)
        self.actionF.setObjectName(_fromUtf8("actionF"))
        self.action_4 = QtGui.QAction(MainWindow)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_5 = QtGui.QAction(MainWindow)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_6 = QtGui.QAction(MainWindow)
        self.action_6.setObjectName(_fromUtf8("action_6"))
        self.action_7 = QtGui.QAction(MainWindow)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.action_8 = QtGui.QAction(MainWindow)
        self.action_8.setObjectName(_fromUtf8("action_8"))
        self.menu.addAction(self.menu_2.menuAction())
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_8)
        self.menu.addAction(self.action_4)
        self.menu_3.addAction(self.action_5)
        self.menu_5.addAction(self.action_6)
        self.menu_5.addAction(self.action_7)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "操作窗", None))
        self.imageLabel.setText(_translate("MainWindow", "imageLabel", None))
        self.capture_btn.setText(_translate("MainWindow", "拍照", None))
        self.label_6.setText(_translate("MainWindow", "获取图像:", None))
        self.label.setText(_translate("MainWindow", "向左移", None))
        self.leftBtn.setText(_translate("MainWindow", "确定", None))
        self.rightBtn_2.setText(_translate("MainWindow", "确定", None))
        self.label_2.setText(_translate("MainWindow", "向右移", None))
        self.label_3.setText(_translate("MainWindow", "向上移", None))
        self.upBtn.setText(_translate("MainWindow", "确定", None))
        self.downBtn.setText(_translate("MainWindow", "确定", None))
        self.label_4.setText(_translate("MainWindow", "向下移", None))
        self.menu.setTitle(_translate("MainWindow", "文件", None))
        self.menu_2.setTitle(_translate("MainWindow", "打开图像..", None))
        self.menu_3.setTitle(_translate("MainWindow", "设置", None))
        self.menu_4.setTitle(_translate("MainWindow", "动作", None))
        self.menu_5.setTitle(_translate("MainWindow", "帮助", None))
        self.action_2.setText(_translate("MainWindow", "重载图片", None))
        self.actionF.setText(_translate("MainWindow", "f", None))
        self.action_4.setText(_translate("MainWindow", "退出", None))
        self.action_5.setText(_translate("MainWindow", "偏好设置", None))
        self.action_6.setText(_translate("MainWindow", "查看帮助", None))
        self.action_7.setText(_translate("MainWindow", "关于", None))
        self.action_8.setText(_translate("MainWindow", "打印输出", None))

