# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_main_window.ui'
#
# Created: Sat May 10 09:21:56 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(793, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.myImageLabel = QtGui.QLabel(self.centralwidget)
        self.myImageLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.myImageLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.myImageLabel.setObjectName(_fromUtf8("myImageLabel"))
        self.verticalLayout.addWidget(self.myImageLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setMaximumSize(QtCore.QSize(16777215, 55))
        self.toolBar.setSizeIncrement(QtCore.QSize(0, 55))
        self.toolBar.setIconSize(QtCore.QSize(20, 22))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.upAction = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/my.qrc/images/71.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upAction.setIcon(icon)
        self.upAction.setObjectName(_fromUtf8("upAction"))
        self.downAction = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/my.qrc/images/44.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downAction.setIcon(icon1)
        self.downAction.setObjectName(_fromUtf8("downAction"))
        self.leftAction = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/my.qrc/images/53.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftAction.setIcon(icon2)
        self.leftAction.setObjectName(_fromUtf8("leftAction"))
        self.rightAction = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/my.qrc/images/64.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightAction.setIcon(icon3)
        self.rightAction.setObjectName(_fromUtf8("rightAction"))
        self.removeAction = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/my.qrc/images/40.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeAction.setIcon(icon4)
        self.removeAction.setObjectName(_fromUtf8("removeAction"))
        self.settingAction = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/my.qrc/images/42.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingAction.setIcon(icon5)
        self.settingAction.setObjectName(_fromUtf8("settingAction"))
        self.open_tmpl_action = QtGui.QAction(MainWindow)
        self.open_tmpl_action.setObjectName(_fromUtf8("open_tmpl_action"))
        self.setTmplAction = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/my.qrc/images/45.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setTmplAction.setIcon(icon6)
        self.setTmplAction.setObjectName(_fromUtf8("setTmplAction"))
        self.captureAction = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/my.qrc/images/54.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.captureAction.setIcon(icon7)
        self.captureAction.setObjectName(_fromUtf8("captureAction"))
        self.addAction = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/my.qrc/images/35.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addAction.setIcon(icon8)
        self.addAction.setObjectName(_fromUtf8("addAction"))
        self.exit_action = QtGui.QAction(MainWindow)
        self.exit_action.setObjectName(_fromUtf8("exit_action"))
        self.about_action = QtGui.QAction(MainWindow)
        self.about_action.setObjectName(_fromUtf8("about_action"))
        self.create_tm_action = QtGui.QAction(MainWindow)
        self.create_tm_action.setObjectName(_fromUtf8("create_tm_action"))
        self.save_tm_action = QtGui.QAction(MainWindow)
        self.save_tm_action.setObjectName(_fromUtf8("save_tm_action"))
        self.switch_cap_action = QtGui.QAction(MainWindow)
        self.switch_cap_action.setObjectName(_fromUtf8("switch_cap_action"))
        self.start_action = QtGui.QAction(MainWindow)
        self.start_action.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/my.qrc/images/34.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_action.setIcon(icon9)
        self.start_action.setObjectName(_fromUtf8("start_action"))
        self.open_camera_action = QtGui.QAction(MainWindow)
        self.open_camera_action.setObjectName(_fromUtf8("open_camera_action"))
        self.close_cam_action = QtGui.QAction(MainWindow)
        self.close_cam_action.setObjectName(_fromUtf8("close_cam_action"))
        self.menu.addAction(self.create_tm_action)
        self.menu.addAction(self.open_tmpl_action)
        self.menu.addAction(self.save_tm_action)
        self.menu.addSeparator()
        self.menu.addAction(self.exit_action)
        self.menu_2.addAction(self.open_camera_action)
        self.menu_2.addAction(self.close_cam_action)
        self.menu_2.addAction(self.switch_cap_action)
        self.menu_3.addAction(self.about_action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.settingAction)
        self.toolBar.addAction(self.addAction)
        self.toolBar.addAction(self.removeAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.upAction)
        self.toolBar.addAction(self.downAction)
        self.toolBar.addAction(self.leftAction)
        self.toolBar.addAction(self.rightAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.setTmplAction)
        self.toolBar.addAction(self.captureAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.start_action)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.settingAction, QtCore.SIGNAL(_fromUtf8("triggered()")), self.myImageLabel.clear)
        QtCore.QObject.connect(self.exit_action, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "主界面", None))
        self.myImageLabel.setText(_translate("MainWindow", "   l", None))
        self.menu.setTitle(_translate("MainWindow", "文件(F)", None))
        self.menu_2.setTitle(_translate("MainWindow", "编辑(E)", None))
        self.menu_3.setTitle(_translate("MainWindow", "帮助(H)", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.upAction.setText(_translate("MainWindow", "向上移", None))
        self.upAction.setToolTip(_translate("MainWindow", "向上移", None))
        self.downAction.setText(_translate("MainWindow", "向下移", None))
        self.downAction.setToolTip(_translate("MainWindow", "向下移", None))
        self.leftAction.setText(_translate("MainWindow", "向左移", None))
        self.leftAction.setToolTip(_translate("MainWindow", "向左移", None))
        self.rightAction.setText(_translate("MainWindow", "向右移", None))
        self.rightAction.setToolTip(_translate("MainWindow", "向右移", None))
        self.removeAction.setText(_translate("MainWindow", "移除元素", None))
        self.removeAction.setToolTip(_translate("MainWindow", "移除元素", None))
        self.settingAction.setText(_translate("MainWindow", "设置", None))
        self.settingAction.setToolTip(_translate("MainWindow", "设置", None))
        self.open_tmpl_action.setText(_translate("MainWindow", "打开模板", None))
        self.open_tmpl_action.setToolTip(_translate("MainWindow", "打开模板", None))
        self.setTmplAction.setText(_translate("MainWindow", "设为模板", None))
        self.setTmplAction.setToolTip(_translate("MainWindow", "设为模板", None))
        self.captureAction.setText(_translate("MainWindow", "拍照", None))
        self.captureAction.setToolTip(_translate("MainWindow", "从摄像头获取模板", None))
        self.addAction.setText(_translate("MainWindow", "添加元素", None))
        self.addAction.setToolTip(_translate("MainWindow", "添加元素", None))
        self.exit_action.setText(_translate("MainWindow", "退出", None))
        self.about_action.setText(_translate("MainWindow", "关于", None))
        self.create_tm_action.setText(_translate("MainWindow", "新建模板", None))
        self.create_tm_action.setToolTip(_translate("MainWindow", "新建模板", None))
        self.save_tm_action.setText(_translate("MainWindow", "保存当前模板", None))
        self.save_tm_action.setToolTip(_translate("MainWindow", "保存当前模板", None))
        self.switch_cap_action.setText(_translate("MainWindow", "切换摄像头", None))
        self.switch_cap_action.setToolTip(_translate("MainWindow", "切换已安装的所有摄像头", None))
        self.start_action.setText(_translate("MainWindow", "开始工作", None))
        self.start_action.setToolTip(_translate("MainWindow", "开始与模板比较工作", None))
        self.open_camera_action.setText(_translate("MainWindow", "打开摄像头", None))
        self.close_cam_action.setText(_translate("MainWindow", "关闭摄像头", None))
        self.close_cam_action.setToolTip(_translate("MainWindow", "关闭摄像头", None))

import ribo_rc
